import { test } from 'ava'
import { compileFromFile } from '../src/index'

const expected = `/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

export interface Referencing {
  foo: ExampleSchema;
}
export interface ExampleSchema {
  firstName: string;
  lastName: string;
  /**
   * Age in years
   */
  age?: number;
  height?: number;
  favoriteFoods?: any[];
  likesDogs?: boolean;
  [k: string]: any;
}
`

export function run() {

  test('compileFromFile should resolve refs from cwd option', async t => {
    const ts = await compileFromFile('./test/resources/other/ReferencingType.json', {cwd: './test/resources'})
    t.is(ts, expected)
  })

}
