/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {ExampleSchema} from 'ReferencedType.ts'
import type {ExampleSchema1} from './inner-dir/ReferencedTypeInInnerDir.ts'
export interface Referencing {
  foo: ExampleSchema
  bar: ExampleSchema1
}
