export const input = {
  title: 'AllOf',
  type: 'object',
  properties: {
    foo: {
      type: 'object',
      allOf: [{$ref: '#/definitions/foo'}, {$ref: '#/definitions/bar'}]
    }
  },
  definitions: {
    foo: {
      properties: {
        a: {type: 'string'},
        b: {type: 'integer'}
      },
      additionalProperties: false,
      required: ['a', 'b']
    },
    bar: {
      properties: {
        a: {type: 'string'}
      },
      additionalProperties: false,
      required: ['a', 'b']
    }
  },
  required: ['foo', 'bar'],
  additionalProperties: false
}

export const output = `/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AllOf {
  foo: Foo & Bar;
}
export interface Foo {
  a: string;
  b: number;
}
export interface Bar {
  a: string;
}
`
