export const input = {
  id: 'Countries',
  type: 'array',
  items: {
    type: 'object',
    properties: {
      id: {
        type: 'string',
        minLength: 2,
        maxLength: 2,
        pattern: '[A-Z]+'
      },
      name: {
        type: 'string'
      }
    },
    required: ['id', 'name']
  }
}

// TODO: Fix indentation
export const output = `/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

export type Countries = {
      id: string;
      name: string;
      [k: string]: any;
    }[];
`
