export const input = {
  properties: {
    bar: {
      anyOf: [
        { type: 'string' },
        { type: 'string' },
        { type: 'integer' },
        { type: 'string' }
      ]
    },
    foo: {
      anyOf: [
        { type: 'string' },
        { type: 'any' },
        { type: 'integer' }
      ]
    }
  },
  required: ['bar', 'foo'],
  title: 'Optimizable Schema',
  type: 'object'
}

export const output = `/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

export interface OptimizableSchema {
  bar: (string | number);
  foo: any;
  [k: string]: any;
}
`
