export const input = {
  title: 'Referencing',
  type: 'object',
  properties: {
    foo: {
      $ref: 'ReferencedTypeWithoutID.json'
    },
    bar: {
      $ref: 'ReferencedTypeWithoutIDConflict.json'
    }
  },
  required: ['foo', 'bar'],
  additionalProperties: false
}

export const options = {
  cwd: 'test/resources/'
}

export const output = `/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

export interface Referencing {
  foo: ExampleSchema;
  bar: ExampleSchema1;
}
export interface ExampleSchema {
  firstName: string;
  lastName: string;
  /**
   * Age in years
   */
  age?: number;
  height?: number;
  favoriteFoods?: any[];
  likesDogs?: boolean;
  [k: string]: any;
}
export interface ExampleSchema1 {
  isConflict: boolean;
}
`
