export const input = {
  "title": "Local Cycle",
  "properties": {
    "foo": {
      "$ref": "#"
    },
    "bar": {
      "$ref": "#"
    }
  },
  "required": ["foo"],
  "additionalProperties": true
}

export const output = `/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

export interface LocalCycle {
  foo: LocalCycle;
  bar?: LocalCycle;
  [k: string]: any;
}
`
