export let exclude = true

export const input = {
  additionalProperties: true,
  properties: {
    foo: {
      $ref: '#/definitions/bar'
    }
  },
  definitions: {
    bar: {
      $ref: '#/definitions/bar'
    }
  },
  required: ['foo'],
  title: 'Cycle (3)'
}

export const output = `/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

export interface Cycle3 {
  foo: Foo;
}
`
