export const input = {
  definitions: {
    definitions: {
      type: 'integer'
    },
    properties: {
      type: 'string'
    }
  },
  properties: {
    additionalProperties: {
      items: {
        type: 'number'
      },
      type: 'array'
    },
    definitions: {
      type: 'number'
    },
    properties: {
      type: 'boolean'
    }
  },
  type: 'object'
}

export const output = `/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ReservedWords {
  additionalProperties?: number[];
  definitions?: number;
  properties?: boolean;
  [k: string]: any;
}
`
